<a href="https://colab.research.google.com/github/hiteshnagar2611/Python_Tutorial/blob/main/Matrix_Intro_%26_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


Creating a matrix using numpy

In [5]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [6]:
matrix_1.shape

(2, 2)

In [7]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,19]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 19]]


In [8]:
matrix_2.shape

(3, 3)

Creating matrix with randome values

In [9]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.01615819 0.12452704 0.81631987]
 [0.32168523 0.28007624 0.3716833 ]
 [0.25459236 0.82785088 0.25236657]]


In [13]:
random_integer_matrix = np.random.randint(10, size=(3,3))
print(random_integer_matrix)

[[2 0 2]
 [3 1 8]
 [9 7 8]]


Matrix with all the values 1

In [14]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
matrix_3 = np.ones((4,4), dtype=int)
print(matrix_3)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


MAtrix of all values 0 (Null Matrix or Zero Matrix)

In [17]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Identity Matrix

In [20]:
identity_matrix = np.eye(4,4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Transpose of Matrix

In [21]:
a = np.random.randint(20, size=(4,4))
print(a)

[[14 14 16  6]
 [14  4 15 18]
 [13 12 15 11]
 [ 6 12 12  1]]


In [22]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[14 14 13  6]
 [14  4 12 12]
 [16 15 15 12]
 [ 6 18 11  1]]


**Matrix Operations**

1. Matrix addition

In [26]:
a = np.array([[2,3],[4,5]])
b = np.array([[6,7],[8,9]])

In [27]:
print(a)

[[2 3]
 [4 5]]


In [28]:
print(b)

[[6 7]
 [8 9]]


In [29]:
a.shape

(2, 2)

In [30]:
b.shape

(2, 2)

In [31]:
sum = a+b
print(sum)

[[ 8 10]
 [12 14]]


In [32]:
a1 = np.random.randint(10, size=(3,3))
b1 = np.random.randint(20, size=(3,3))
print(a1)
print(b1)

sum1 = a1+b1
print(sum1)

[[8 9 8]
 [5 1 7]
 [7 8 9]]
[[16  7 14]
 [ 5  1 17]
 [13  0  8]]
[[24 16 22]
 [10  2 24]
 [20  8 17]]


In [33]:
# gives ERROR because both size of matrix is not same 3X2 and 3X3
a1 = np.random.randint(10, size=(3,2))
b1 = np.random.randint(20, size=(3,3))
print(a1)
print(b1)

sum1 = a1+b1
print(sum1)

[[8 9]
 [3 1]
 [5 1]]
[[ 7 10  1]
 [10 13  0]
 [18 12 15]]


ValueError: operands could not be broadcast together with shapes (3,2) (3,3) 

2. Matrix Subtraction

In [35]:
a2 = np.random.randint(10, size=(3,3))
b2 = np.random.randint(20, size=(3,3))
print(a2)
print(b2)

sub = a2 - b2
print(sub)

[[5 1 4]
 [1 0 2]
 [3 4 6]]
[[10  1 17]
 [ 2 10 12]
 [ 8 13  3]]
[[ -5   0 -13]
 [ -1 -10 -10]
 [ -5  -9   3]]


3. Multiplication by a scaler

In [37]:
a3 = np.random.randint(10, size=(3,3))
print(a3)

multiply_by_scaler =  4 * a3
print(multiply_by_scaler)

[[4 6 2]
 [3 1 6]
 [3 7 3]]
[[16 24  8]
 [12  4 24]
 [12 28 12]]


4. Multiplication

In [38]:
a4 = np.random.randint(10, size=(3,3))
b4 = np.random.randint(20, size=(3,3))
print(a4)
print(b4)

multi = a4 * b4
print(multi)

[[2 2 5]
 [0 6 2]
 [2 7 2]]
[[ 1 18  0]
 [ 7 13  2]
 [13 10 16]]
[[ 2 36  0]
 [ 0 78  4]
 [26 70 32]]


In [39]:
# Gives ERROR because column of first matrix is not eqaul to row of second matrix
a4 = np.random.randint(10, size=(3,4))
b4 = np.random.randint(20, size=(3,3))
print(a4)
print(b4)

multi = a4 * b4
print(multi)

[[5 5 8 2]
 [0 4 1 1]
 [2 7 8 4]]
[[16 14 10]
 [ 9 12  4]
 [16  9  8]]


ValueError: operands could not be broadcast together with shapes (3,4) (3,3) 