<a href="https://colab.research.google.com/github/hiteshnagar2611/Python_Tutorial/blob/main/Matrix_Intro_%26_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


Creating a matrix using numpy

In [5]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [6]:
matrix_1.shape

(2, 2)

In [7]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,19]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 19]]


In [8]:
matrix_2.shape

(3, 3)

Creating matrix with randome values

In [9]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.01615819 0.12452704 0.81631987]
 [0.32168523 0.28007624 0.3716833 ]
 [0.25459236 0.82785088 0.25236657]]


In [13]:
random_integer_matrix = np.random.randint(10, size=(3,3))
print(random_integer_matrix)

[[2 0 2]
 [3 1 8]
 [9 7 8]]


Matrix with all the values 1

In [14]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
matrix_3 = np.ones((4,4), dtype=int)
print(matrix_3)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


MAtrix of all values 0 (Null Matrix or Zero Matrix)

In [17]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Identity Matrix

In [20]:
identity_matrix = np.eye(4,4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Transpose of Matrix

In [21]:
a = np.random.randint(20, size=(4,4))
print(a)

[[14 14 16  6]
 [14  4 15 18]
 [13 12 15 11]
 [ 6 12 12  1]]


In [22]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[14 14 13  6]
 [14  4 12 12]
 [16 15 15 12]
 [ 6 18 11  1]]
